### ISSUE TITLE
New Code definition in Sonar

### ISSUE THREAD

**Issue by alce65** [isdi-coders-2022/Meta-Azul-202210-mad#52]
Hola chic@s
Os falta en Sonar la definición de New Code.
Podéis poner la que queráis, pero poner alguna.
Un par de grupos ya lo tienen, así que podéis preguntarles.

**Comment by PatriciaTellezG** [comment]
Hola Alejandro, 
Lo acabamos de cambiar a la versión previa, en el siguiente análisis ya estará funcionando.
Gracias por avisarnos!

**Comment by alce65** [comment]
Genial.
Cierro el issue
