### ISSUE TITLE
PRs Review

### ISSUE THREAD

**Issue by alce65** [isdi-coders-2022/Meta-Azul-202210-mad#54]
Estáis aprobando PRs que fallan en el despliegue de Netlify ¿Sabeis por qué? ¿Sois conscientes de que no estarías manteniendo actualizado vuestro despliegue a producción?. O peor aún, quizás ni siquiera funcione.
Echar un vistazo o contarme que es lo que pasa.

Por otro lado, también tenéis algunas hace unos días aprobados con fallos en Sonar. ¿Entendéis que no debería ser así? El objetivo de integrar Sonar en nuestro flujo CI/CD es que no llegue a producción software que no cumple con los criterios de calidad que nosotros mismos nos hemos impuesto.

Ya se que vais con prisas, pero esto pasa siempre. Se que lo dejareis bien al final, pero lo siguiente es conseguir tenerlo bien de forma continuada (de ahí el CI/CD)

Mucho ánimo, que ya os queda poco.

**Comment by Liluminalia** [comment]
buenas alejandro, si llevas razon, teniamos esa intencion pero al estar perdidas con algunas cosas es cierto que no nos hemos dado cuenta y lo hemos dejado mas de lado, vamos a intentar que este correctamente actualizado lo antes posible, muchas gracias!

**Comment by alce65** [comment]
No hay problema.
Cierro el issue
